import { readInputTarget, resolveInputTarget, updateAgentCursor } from './collector';
import { scriptTarget } from './frames';

type Target = { ok: boolean; code?: string; error?: string; x?: number; y?: number; tag?: string; type?: string; editable?: boolean; contentEditable?: boolean; value?: string; checked?: boolean; select?: boolean };
type Command = (target: chrome.debugger.Debuggee, method: string, params?: Record<string, unknown>) => Promise<unknown>;
const inputTools = new Set(['click', 'double_click', 'hover', 'focus', 'scroll', 'type', 'fill', 'paste_text', 'clear', 'press_key', 'check', 'uncheck', 'select_option', 'submit_form']);
const specialKeys: Record<string, { code: string; vk: number }> = { Enter: { code: 'Enter', vk: 13 }, Tab: { code: 'Tab', vk: 9 }, Escape: { code: 'Escape', vk: 27 }, ArrowLeft: { code: 'ArrowLeft', vk: 37 }, ArrowUp: { code: 'ArrowUp', vk: 38 }, ArrowRight: { code: 'ArrowRight', vk: 39 }, ArrowDown: { code: 'ArrowDown', vk: 40 }, Backspace: { code: 'Backspace', vk: 8 }, Delete: { code: 'Delete', vk: 46 }, Home: { code: 'Home', vk: 36 }, End: { code: 'End', vk: 35 }, PageUp: { code: 'PageUp', vk: 33 }, PageDown: { code: 'PageDown', vk: 34 }, Space: { code: 'Space', vk: 32 } };

export class InputController {
  private attached = new Set<number>(); private queues = new Map<number, Promise<unknown>>(); private generations = new Map<number, number>(); private positions = new Map<number, { x: number; y: number }>();
  constructor(private command: Command = (target, method, params) => chrome.debugger.sendCommand(target, method, params)) {}
  handles(tool: string) { return inputTools.has(tool); }
  run(tabId: number, tool: string, args: Record<string, unknown>, visibleCursor = true) {
    const generation = this.generations.get(tabId) ?? 0;
    const task = (this.queues.get(tabId) ?? Promise.resolve()).catch(() => undefined).then(() => this.perform(tabId, tool, args, visibleCursor, generation));
    this.queues.set(tabId, task); task.finally(() => { if (this.queues.get(tabId) === task) this.queues.delete(tabId); }).catch(() => undefined); return task;
  }
  async cleanup(tabId?: number) {
    const ids = tabId === undefined ? [...new Set([...this.attached, ...this.queues.keys()])] : [tabId];
    await Promise.all(ids.map(async id => { this.generations.set(id, (this.generations.get(id) ?? 0) + 1); this.queues.delete(id); await this.overlay(id, undefined, undefined, false, false, true).catch(() => undefined); if (this.attached.has(id)) { await this.release(id).catch(() => undefined); await chrome.debugger.detach({ tabId: id }).catch(() => undefined); this.attached.delete(id); } this.positions.delete(id); }));
  }
  markDetached(tabId?: number) { if (tabId !== undefined) this.attached.delete(tabId); }
  private cancelled(tabId: number, generation: number) { return (this.generations.get(tabId) ?? 0) !== generation; }
  private async attach(tabId: number) { if (this.attached.has(tabId)) return; try { await chrome.debugger.attach({ tabId }, '1.3'); this.attached.add(tabId); } catch (error) { throw new Error(`Browser-level input is unavailable. Close DevTools or another debugger attached to this tab, then resume. ${error instanceof Error ? error.message : String(error)}`); } }
  private async resolve(tabId: number, args: Record<string, unknown>): Promise<Target> { const [{ result }] = await chrome.scripting.executeScript({ target: scriptTarget(tabId, args), func: resolveInputTarget, args: [args.elementId as string | undefined, args.documentToken as string | undefined] }); return result as Target; }
  private async overlay(tabId: number, x?: number, y?: number, visible = true, click = false, remove = false) { await chrome.scripting.executeScript({ target: { tabId }, func: updateAgentCursor, args: [x, y, visible, click, remove] }); }
  private async move(tabId: number, x: number, y: number, visible: boolean, generation: number) { const from = this.positions.get(tabId) ?? { x, y }; await this.overlay(tabId, x, y, visible); for (let i = 1; i <= 10; i++) { if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.'); const p = i / 10; await this.command({ tabId }, 'Input.dispatchMouseEvent', { type: 'mouseMoved', x: from.x + (x - from.x) * p, y: from.y + (y - from.y) * p }); await new Promise(resolve => setTimeout(resolve, 14)); } this.positions.set(tabId, { x, y }); }
  private async mouse(tabId: number, x: number, y: number, count = 1) { for (let i = 1; i <= count; i++) { await this.command({ tabId }, 'Input.dispatchMouseEvent', { type: 'mousePressed', x, y, button: 'left', clickCount: i }); await this.command({ tabId }, 'Input.dispatchMouseEvent', { type: 'mouseReleased', x, y, button: 'left', clickCount: i }); } }
  private async key(tabId: number, expression: string) { const parts = expression.split('+'); const key = parts.pop() || expression; let modifiers = 0; for (const part of parts) { if (/^(ctrl|control)$/i.test(part)) modifiers |= 2; else if (/alt/i.test(part)) modifiers |= 1; else if (/shift/i.test(part)) modifiers |= 8; else if (/^(meta|cmd|command)$/i.test(part)) modifiers |= 4; } const info = specialKeys[key] ?? { code: /^.$/u.test(key) ? `Key${key.toUpperCase()}` : key, vk: /^.$/u.test(key) ? key.toUpperCase().charCodeAt(0) : 0 }; await this.command({ tabId }, 'Input.dispatchKeyEvent', { type: 'rawKeyDown', key: key === 'Space' ? ' ' : key, code: info.code, windowsVirtualKeyCode: info.vk, nativeVirtualKeyCode: info.vk, modifiers }); await this.command({ tabId }, 'Input.dispatchKeyEvent', { type: 'keyUp', key: key === 'Space' ? ' ' : key, code: info.code, windowsVirtualKeyCode: info.vk, nativeVirtualKeyCode: info.vk, modifiers }); }
  private async insert(tabId: number, value: string, generation: number) { if ([...value].length > 200) { await this.command({ tabId }, 'Input.insertText', { text: value }); return; } for (const char of value) { if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.'); await this.command({ tabId }, 'Input.insertText', { text: char }); await new Promise(resolve => setTimeout(resolve, 25)); } }
  private async read(tabId: number, args: Record<string, unknown>) { const [{ result }] = await chrome.scripting.executeScript({ target: scriptTarget(tabId, args), func: readInputTarget, args: [args.elementId as string | undefined, args.documentToken as string | undefined] }); return result as { exists: boolean; value?: string; checked?: boolean; selected?: string }; }
  private async release(tabId: number) { const position = this.positions.get(tabId) ?? { x: 0, y: 0 }; await this.command({ tabId }, 'Input.dispatchMouseEvent', { type: 'mouseReleased', ...position, button: 'left', clickCount: 1 }); for (const key of ['Control', 'Alt', 'Shift', 'Meta']) await this.command({ tabId }, 'Input.dispatchKeyEvent', { type: 'keyUp', key }); }
  private async perform(tabId: number, tool: string, args: Record<string, unknown>, visible: boolean, generation: number) {
    if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.'); await this.attach(tabId); if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.');
    if (tool === 'scroll') { const target = args.elementId ? await this.resolve(tabId, args) : undefined; if (target && !target.ok) return target; if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.'); const amount = Math.abs(Number(args.amount ?? 600)) * (args.direction === 'up' ? -1 : 1); await this.command({ tabId }, 'Input.dispatchMouseEvent', { type: 'mouseWheel', x: target?.x ?? this.positions.get(tabId)?.x ?? 10, y: target?.y ?? this.positions.get(tabId)?.y ?? 10, deltaX: 0, deltaY: amount }); return { ok: true }; }
    const target = await this.resolve(tabId, args); if (!target.ok) return target; const x = target.x!; const y = target.y!; await this.move(tabId, x, y, visible, generation);
    if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.');
    const currentTarget = await this.resolve(tabId, args);
    if (!currentTarget.ok) return currentTarget;
    if (Math.abs(currentTarget.x! - x) > 1 || Math.abs(currentTarget.y! - y) > 1) return { ok: false, code: 'STALE_ELEMENT', error: 'The target moved while approaching it; observe again before clicking.' };
    if (this.cancelled(tabId, generation)) throw new Error('Browser input was cancelled.');
    if (tool === 'hover') return { ok: true };
    if (['click', 'double_click', 'focus', 'submit_form', 'check', 'uncheck'].includes(tool)) { if ((tool === 'check' && target.checked) || (tool === 'uncheck' && !target.checked)) return { ok: true }; await this.overlay(tabId, x, y, visible, true); await this.mouse(tabId, x, y, tool === 'double_click' ? 2 : 1); if (tool === 'submit_form' && target.tag !== 'BUTTON' && target.type !== 'submit') await this.key(tabId, 'Enter'); if (tool === 'check' || tool === 'uncheck') { const state = await this.read(tabId, args); if (state.checked !== (tool === 'check')) return { ok: false, code: 'INPUT_MISMATCH', error: 'The checkbox did not retain the requested state.' }; } return { ok: true, needsSubmissionVerification: tool === 'submit_form' }; }
    await this.overlay(tabId, x, y, visible, true); await this.mouse(tabId, x, y);
    if (tool === 'press_key') { await this.key(tabId, String(args.key)); return { ok: true, needsSubmissionVerification: args.key === 'Enter' }; }
    if (tool === 'select_option') { await this.insert(tabId, String(args.value ?? ''), generation); await this.key(tabId, 'Enter'); const state = await this.read(tabId, args); return state.selected === String(args.value) ? { ok: true } : { ok: false, code: 'INPUT_MISMATCH', error: 'The option did not retain the requested value.' }; }
    if (!target.editable) return { ok: false, code: 'NOT_EDITABLE', error: 'The target does not accept text.' };
    await this.key(tabId, 'Control+A'); await this.key(tabId, 'Backspace'); const value = tool === 'clear' ? '' : String(args.value ?? ''); if (value) await this.insert(tabId, value, generation); const state = await this.read(tabId, args); return state.value === value ? { ok: true } : { ok: false, code: 'INPUT_MISMATCH', error: 'The field did not retain the requested text.' };
  }
}
